server: 
  port: 90
  servlet:
    encoding:
      charset: utf-8
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://13.209.99.222:3306/CUGGI?serverTimeZone=Asia/Seoul&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: awskjh
    password: 7193asd
    
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: cuggishopateam # 3
    password: ooie ooxh mxxw gxxn # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
            
# 파일업로드            
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 10MB
  
file:
  path: c:\upload\  
        
      
#  sql:  
#    init:
#      schema-locations:
#      - classpath:db/table.sql
#      data-locations:
#      - classpath:db/data.sql
  
#  h2:
#    console:
#      enabled: true
#  output:
#   ansi: 
#     enabled: always   
  
mybatis:
  mapper-locations:
  - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    
# 초기 파라미터 설정    
tenco:
  key: 85135F3C6BFE9DF1735F8806F045AE73CECE7219F7840D8E7E9297A7F846B48A

#logging:
  #level:
    #'[org.mybatis]': DEBUG
    


        